apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp2
  name: demoapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp2
  strategy: {}
  template:
    metadata:
      labels:
        app: demoapp2
    spec:
      containers:
      - image: wfsilva/demoapp:v3
        name: demoapp
        ports:
        - containerPort: 8080
        resources: {}
