apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp1
  name: demoapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp1
  template:
    metadata:
      labels:
        app: demoapp1
    spec:
      containers:
      - image: wfsilva/demoapp:v1
        name: demoapp
        ports:
        - containerPort: 8080
